###
# Returns the details of a single bulk action.
GET {{url}}
Accept application/json

""


###
# Removes the specified action from the list of bulk actions.
DELETE {{url}}
Accept text/plain

""


###
# Returns the results of a bulk action as a CSV.
GET {{url}}
Accept text/csv

""


###
# Gets a list of all the bulk actions.
GET {{url}}
Accept application/json

""


###
# Gets information about a specific jurisdiction.
GET {{url}}
Accept application/json

""


###
# Gets a list of supported jurisdictions.
GET {{url}}
Accept application/json

""


###
# Returns the notary specified by the user ID.
GET {{url}}
Accept application/json

""


###
# Returns a list of available notaries.
GET {{url}}
Accept application/json

""


###
# Gets the set of pools associated with the current account.
GET {{url}}
Accept application/json

""


###
# Creates a new pool of remote notaries.
POST {{url}}
Content-Type application/json
Accept application/json

"{
  "name": "<string>",
  "organizationId": "<uuid>"
}"


###
# Gets a list of all the notary pool invites given a pool's ID.
GET {{url}}
Accept application/json

""


###
# Creates an invite for a remote notary to join a pool.
POST {{url}}
Content-Type application/json
Accept application/json

"{
  "email": "<string>",
  "name": "<string>"
}"


###
# Resends a pool invite.
POST {{url}}
Accept application/json

""


###
# Deletes a pending pool invite.
DELETE {{url}}
Accept text/plain

""


###
# Invites multiple remote notaries to join a pool.
POST {{url}}
Content-Type application/x-www-form-urlencoded
Accept application/json

""


###
# Gets a pool user by pool ID and user ID.
GET {{url}}
Accept application/json

""


###
# Deletes a remote notary from a pool.
DELETE {{url}}
Accept text/plain

""


###
# Gets a list of remote notaries in a pool
GET {{url}}
Accept application/json

""


###
# Gets a list of notary pools that a notary belongs to.
GET {{url}}
Accept application/json

""


###
# Get information about a notary's commission.
GET {{url}}
Accept application/json

""


###
# Gets the notary seal image.
GET {{url}}
Accept text/plain

""


###
# Gets a list of a remote notary's commissions.
GET {{url}}
Accept application/json

""


###
# Retrieves a list of the supported identification documents.
GET {{url}}
Accept application/json

""


###
# Retrieves a list of the supported notarization types.
GET {{url}}
Accept application/json

""


###
# Retrieves a list of the supported seal types.
GET {{url}}
Accept application/json

""


###
# Retrieves a list of the supported states.
GET {{url}}
Accept application/json

""


###
# Gets a list of journal sessions for a given user.
GET {{url}}
Accept application/json

""


###
# Gets a notary's complete journal as a PDF file.
GET {{url}}
Accept application/pdf

""


###
# Retrieves a PDF of a specified journal entry.
GET {{url}}
Accept application/pdf

""


