###
# Returns the details of a single bulk action.
GET test.com.br
Accept application/json
Content-Type application/json

{}


###
# Removes the specified action from the list of bulk actions.
DELETE {{url}}
Accept text/plain
Content-Type application/json

{}


